import SwiftCompilerPlugin
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

/// Base macro for HTTP method annotations
public protocol HTTPMethodMacro: PeerMacro {}

/// Macro for @GET annotations
public struct GETMacro: HTTPMethodMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    // HTTP method macros are informational only
    // The actual implementation is generated by APIMacro
    []
  }
}

/// Macro for @POST annotations
public struct POSTMacro: HTTPMethodMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    []
  }
}

/// Macro for @PUT annotations
public struct PUTMacro: HTTPMethodMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    []
  }
}

/// Macro for @DELETE annotations
public struct DELETEMacro: HTTPMethodMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    []
  }
}

/// Macro for @PATCH annotations
public struct PATCHMacro: HTTPMethodMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    []
  }
}
