import Foundation

// MARK: - Markdown Report Generator

/// Generates Markdown reports from test execution data.
///
/// ```swift
/// let generator = MarkdownReportGenerator()
/// let markdown = generator.generate(from: reportData)
///
/// // Write to file
/// try generator.write(to: URL(fileURLWithPath: "report.md"), from: reportData)
/// ```
public struct MarkdownReportGenerator: Sendable {
  // MARK: - Configuration

  /// Configuration for report generation.
  public struct Configuration: Sendable {
    /// Include step details in the report.
    public let includeSteps: Bool

    /// Include duration information.
    public let includeDuration: Bool

    /// Include error details.
    public let includeErrors: Bool

    /// Include tags in scenario headers.
    public let includeTags: Bool

    /// Date formatter for timestamps.
    public let dateFormat: String

    /// Creates a configuration.
    public init(
      includeSteps: Bool = true,
      includeDuration: Bool = true,
      includeErrors: Bool = true,
      includeTags: Bool = true,
      dateFormat: String = "yyyy-MM-dd HH:mm:ss"
    ) {
      self.includeSteps = includeSteps
      self.includeDuration = includeDuration
      self.includeErrors = includeErrors
      self.includeTags = includeTags
      self.dateFormat = dateFormat
    }

    /// Default configuration.
    public static var `default`: Self { Self() }
  }

  // MARK: - Properties

  private let configuration: Configuration

  // MARK: - Initialization

  /// Creates a markdown report generator.
  ///
  /// - Parameter configuration: Generation configuration
  public init(configuration: Configuration = .default) {
    self.configuration = configuration
  }

  // MARK: - Generation

  /// Generates a markdown report.
  ///
  /// - Parameter data: Report data from collector
  /// - Returns: Markdown formatted string
  public func generate(from data: ReportCollector.ReportData) -> String {
    var lines: [String] = []

    // Title
    lines.append("# \(data.title)")
    lines.append("")

    // Timestamp
    let formatter = DateFormatter()
    formatter.dateFormat = configuration.dateFormat
    lines.append("Generated: \(formatter.string(from: data.timestamp))")
    lines.append("")

    // Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(generateSummaryTable(data.summary))
    lines.append("")

    // Pass rate badge
    lines.append(generatePassRateBadge(data.summary.passRate))
    lines.append("")

    // Features
    lines.append("## Features")
    lines.append("")

    for feature in data.features {
      lines.append(generateFeatureSection(feature))
    }

    // Footer
    lines.append("---")
    lines.append("*Generated by BDD Test Framework*")

    return lines.joined(separator: "\n")
  }

  /// Writes a markdown report to file.
  ///
  /// - Parameters:
  ///   - url: File URL to write to
  ///   - data: Report data
  public func write(to url: URL, from data: ReportCollector.ReportData) throws {
    let content = generate(from: data)
    try content.write(to: url, atomically: true, encoding: .utf8)
  }

  // MARK: - Private Methods

  private func generateSummaryTable(_ summary: ReportCollector.ReportData.Summary) -> String {
    var lines: [String] = []

    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append("| Total Scenarios | \(summary.totalScenarios) |")
    lines.append("| Passed | \(summary.passedScenarios) |")
    lines.append("| Failed | \(summary.failedScenarios) |")
    lines.append("| Skipped | \(summary.skippedScenarios) |")
    lines.append("| Pending | \(summary.pendingScenarios) |")
    lines.append("| Total Steps | \(summary.totalSteps) |")
    lines.append("| Pass Rate | \(String(format: "%.1f", summary.passRate))% |")

    if configuration.includeDuration {
      lines.append("| Duration | \(formatDuration(summary.totalDuration)) |")
    }

    return lines.joined(separator: "\n")
  }

  private func generatePassRateBadge(_ passRate: Double) -> String {
    let color: String
    if passRate >= 90 {
      color = "brightgreen"
    } else if passRate >= 70 {
      color = "yellow"
    } else {
      color = "red"
    }

    let percentage = String(format: "%.0f", passRate)
    return "![Pass Rate](https://img.shields.io/badge/pass%20rate-\(percentage)%25-\(color))"
  }

  private func generateFeatureSection(_ feature: ReportCollector.ReportData.FeatureReport) -> String {
    var lines: [String] = []

    let featureIcon = feature.failedCount > 0 ? "X" : "V"
    lines.append("### \(featureIcon) \(feature.name)")
    lines.append("")

    if configuration.includeDuration {
      lines.append("Duration: \(formatDuration(feature.duration))")
      lines.append("")
    }

    // Scenarios table
    lines.append("| Status | Scenario | Duration |")
    lines.append("|--------|----------|----------|")

    for scenario in feature.scenarios {
      let icon = statusIcon(for: scenario.status)
      let duration = configuration.includeDuration ? formatDuration(scenario.duration) : "-"
      var scenarioName = scenario.scenarioName

      if configuration.includeTags && !scenario.tags.isEmpty {
        let tags = scenario.tags.map { "`\($0)`" }.joined(separator: " ")
        scenarioName = "\(scenarioName) \(tags)"
      }

      lines.append("| \(icon) | \(scenarioName) | \(duration) |")

      // Add error details if failed
      if configuration.includeErrors, let error = scenario.error, scenario.status == .failed {
        lines.append("")
        lines.append("<details>")
        lines.append("<summary>Error Details</summary>")
        lines.append("")
        lines.append("```")
        lines.append(error)
        lines.append("```")
        lines.append("</details>")
        lines.append("")
      }

      // Add step details
      if configuration.includeSteps && !scenario.steps.isEmpty {
        lines.append("")
        lines.append("<details>")
        lines.append("<summary>Steps</summary>")
        lines.append("")
        for step in scenario.steps {
          let stepIcon = statusIcon(for: step.status)
          lines.append("- \(stepIcon) **\(step.keyword)** \(step.text)")
          if let error = step.error, step.status == .failed {
            lines.append("  - Error: `\(error)`")
          }
        }
        lines.append("</details>")
        lines.append("")
      }
    }

    lines.append("")
    return lines.joined(separator: "\n")
  }

  private func statusIcon(for status: ReportCollector.TestResult.Status) -> String {
    switch status {
    case .passed: return "PASS"
    case .failed: return "FAIL"
    case .skipped: return "SKIP"
    case .pending: return "PEND"
    }
  }

  private func formatDuration(_ duration: TimeInterval) -> String {
    if duration < 1 {
      return String(format: "%.0fms", duration * 1000)
    } else if duration < 60 {
      return String(format: "%.2fs", duration)
    } else {
      let minutes = Int(duration / 60)
      let seconds = duration.truncatingRemainder(dividingBy: 60)
      return String(format: "%dm %.2fs", minutes, seconds)
    }
  }
}
