import NetworkingRuntime
import NetworkingTesting
import Foundation

// MARK: - Markdown Report Generator

/// Generates Markdown reports from test execution data.
///
/// ```swift
/// let generator = MarkdownReportGenerator()
/// let markdown = generator.generate(from: reportData)
///
/// // Write to file
/// try generator.write(to: URL(fileURLWithPath: "report.md"), from: reportData)
/// ```
public struct MarkdownReportGenerator: Sendable {
  // MARK: - Configuration

  /// Configuration for report generation.
  public struct Configuration: Sendable {
    public enum StepInclusion: Sendable {
      case included
      case omitted

      var includesSteps: Bool { self == .included }
    }

    public enum DurationInclusion: Sendable {
      case included
      case omitted

      var includesDuration: Bool { self == .included }
    }

    public enum ErrorInclusion: Sendable {
      case included
      case omitted

      var includesErrors: Bool { self == .included }
    }

    public enum TagInclusion: Sendable {
      case included
      case omitted

      var includesTags: Bool { self == .included }
    }

    /// Include step details in the report.
    public let includeSteps: StepInclusion

    /// Include duration information.
    public let includeDuration: DurationInclusion

    /// Include error details.
    public let includeErrors: ErrorInclusion

    /// Include tags in scenario headers.
    public let includeTags: TagInclusion

    /// Date formatter for timestamps.
    public let dateFormat: UserMessageText

    /// Creates a configuration.
    public init(
      includeSteps: StepInclusion = .included,
      includeDuration: DurationInclusion = .included,
      includeErrors: ErrorInclusion = .included,
      includeTags: TagInclusion = .included,
      dateFormat: UserMessageText = "yyyy-MM-dd HH:mm:ss"
    ) {
      self.includeSteps = includeSteps
      self.includeDuration = includeDuration
      self.includeErrors = includeErrors
      self.includeTags = includeTags
      self.dateFormat = dateFormat
    }

    /// Default configuration.
    public static var `default`: Self { Self() }
  }

  // MARK: - Properties

  let configuration: Configuration

  // MARK: - Initialization

  /// Creates a markdown report generator.
  ///
  /// - Parameter configuration: Generation configuration
  public init(configuration: Configuration = .default) {
    self.configuration = configuration
  }

  // MARK: - Generation

  /// Generates a markdown report.
  ///
  /// - Parameter data: Report data from collector
  /// - Returns: Markdown formatted string
  public func generate(from data: ReportCollector.ReportData) -> UserMessageText {
    var lines: [String] = []

    // Title
    lines.append("# \(data.title.rawValue)")
    lines.append("")

    // Timestamp
    let formatter = DateFormatter()
    formatter.dateFormat = configuration.dateFormat.rawValue
    lines.append("Generated: \(formatter.string(from: data.timestamp))")
    lines.append("")

    // Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(generateSummaryTable(data.summary).rawValue)
    lines.append("")

    // Pass rate badge
    lines.append(generatePassRateBadge(data.summary.passRate).rawValue)
    lines.append("")

    // Features
    lines.append("## Features")
    lines.append("")

    for feature in data.features {
      lines.append(generateFeatureSection(feature).rawValue)
    }

    // Footer
    lines.append("---")
    lines.append("*Generated by BDD Test Framework*")

    return UserMessageText(lines.joined(separator: "\n"))
  }

  /// Writes a markdown report to file.
  ///
  /// - Parameters:
  ///   - url: File URL to write to
  ///   - data: Report data
  public func write(to url: BDDFileURL, from data: ReportCollector.ReportData) throws {
    let content = generate(from: data)
    try content.rawValue.write(to: url.rawValue, atomically: true, encoding: .utf8)
  }

  // MARK: - Private Methods

  private func generateSummaryTable(
    _ summary: ReportCollector.ReportData.Summary
  ) -> UserMessageText {
    var lines: [String] = []

    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append("| Total Scenarios | \(summary.totalScenarios) |")
    lines.append("| Passed | \(summary.passedScenarios) |")
    lines.append("| Failed | \(summary.failedScenarios) |")
    lines.append("| Skipped | \(summary.skippedScenarios) |")
    lines.append("| Pending | \(summary.pendingScenarios) |")
    lines.append("| Total Steps | \(summary.totalSteps) |")
    lines.append("| Pass Rate | \(String(format: "%.1f", summary.passRate.rawValue))% |")

    if configuration.includeDuration.includesDuration {
      lines.append("| Duration | \(formatDuration(summary.totalDuration).rawValue) |")
    }

    return UserMessageText(lines.joined(separator: "\n"))
  }

  private func generatePassRateBadge(_ passRate: BDDPassRate) -> UserMessageText {
    let color: String
    if passRate.rawValue >= 90 {
      color = "brightgreen"
    } else if passRate.rawValue >= 70 {
      color = "yellow"
    } else {
      color = "red"
    }

    let percentage = String(format: "%.0f", passRate.rawValue)
    return UserMessageText(
      "![Pass Rate](https://img.shields.io/badge/pass%20rate-\(percentage)%25-\(color))"
    )
  }

  private func generateFeatureSection(
    _ feature: ReportCollector.ReportData.FeatureReport
  ) -> UserMessageText {
    var lines = featureSectionHeaderLines(for: feature)
    for scenario in feature.scenarios {
      lines.append(contentsOf: scenarioSectionLines(for: scenario))
    }
    lines.append("")
    return UserMessageText(lines.joined(separator: "\n"))
  }

  func statusIcon(for status: ReportCollector.TestResult.Status) -> UserMessageText {
    switch status {
    case .passed: return UserMessageText("PASS")
    case .failed: return UserMessageText("FAIL")
    case .skipped: return UserMessageText("SKIP")
    case .pending: return UserMessageText("PEND")
    }
  }

  func formatDuration(_ duration: MeasurementDuration) -> UserMessageText {
    if duration.rawValue < 1 {
      return UserMessageText(String(format: "%.0fms", duration.rawValue * 1000))
    } else if duration.rawValue < 60 {
      return UserMessageText(String(format: "%.2fs", duration.rawValue))
    } else {
      let minutes = Int(duration.rawValue / 60)
      let seconds = duration.rawValue.truncatingRemainder(dividingBy: 60)
      return UserMessageText(String(format: "%dm %.2fs", minutes, seconds))
    }
  }
}
