import Foundation

public enum ObservabilityURLTextTag: Sendable {}
public enum ObservabilityHostNameTag: Sendable {}
public enum ObservabilityPathTextTag: Sendable {}
public enum ObservabilityBodySizeTag: Sendable {}
public enum ObservabilityUserAgentTag: Sendable {}
public enum CorrelationIdentifierTag: Sendable {}
public enum SessionIdentifierTag: Sendable {}
public enum UserIdentifierTag: Sendable {}
public enum DeviceIdentifierTag: Sendable {}
public enum AppVersionTextTag: Sendable {}
public enum PlatformNameTag: Sendable {}
public enum NetworkTypeNameTag: Sendable {}
public enum ObservabilityTagNameTag: Sendable {}
public enum ObservabilityTagValueTag: Sendable {}
public enum StatusCategoryTextTag: Sendable {}
public enum ResponseSizeTag: Sendable {}
public enum CompressionRatioValueTag: Sendable {}
public enum ErrorRateValueTag: Sendable {}
public enum ThroughputValueTag: Sendable {}
public enum CacheHitRateValueTag: Sendable {}
public enum RetryRateValueTag: Sendable {}
public enum ActiveConnectionCountTag: Sendable {}
public enum RequestCountTag: Sendable {}
public enum EndpointIdentifierTag: Sendable {}
public enum ObservabilityErrorTypeTag: Sendable {}
public enum ObservabilityErrorCategoryTag: Sendable {}
public enum UnderlyingErrorTextTag: Sendable {}
public enum NetworkConditionTextTag: Sendable {}
public enum ServerStatusTextTag: Sendable {}
public enum CollectHeadersFlagTag: Sendable {}
public enum CollectBodyInfoFlagTag: Sendable {}
public enum CollectDetailedMetricsFlagTag: Sendable {}
public enum MetricsCollectionDecisionTag: Sendable {}
public enum ObservabilityDecisionTag: Sendable {}
public enum EnableTracingFlagTag: Sendable {}
public enum CollectBusinessMetricsFlagTag: Sendable {}
public enum TracingSampleRateTag: Sendable {}
public enum MaxActiveTraceCountTag: Sendable {}
public enum ActiveTraceCountTag: Sendable {}
public enum MetricsReportingIntervalTag: Sendable {}
public enum EnableRealtimeMetricsFlagTag: Sendable {}
public enum MetricsRetentionDurationTag: Sendable {}
public enum RedactedHeaderNameTag: Sendable {}
public enum EventIdentifierTag: Sendable {}
public enum PersistenceDirectoryTag: Sendable {}
public enum EnablePersistenceFlagTag: Sendable {}
public enum EnableAlertingFlagTag: Sendable {}
public enum EventRetentionDurationTag: Sendable {}
public enum MetricsWindowSizeTag: Sendable {}
public enum MeasurementDurationTag: Sendable {}
public enum MaxEventsInMemoryTag: Sendable {}
public enum DailyActiveUserCountTag: Sendable {}
public enum SessionCountTag: Sendable {}
public enum ConversionRateTag: Sendable {}
public enum UserRetentionRateTag: Sendable {}
public enum AlertTitleTag: Sendable {}
public enum AlertMessageTag: Sendable {}
public enum AlertMetricNameTag: Sendable {}
public enum AlertThresholdValueTag: Sendable {}
public enum RequestSuccessFlagTag: Sendable {}
public enum MaxConcurrentTimingCountTag: Sendable {}
public enum ActiveTimingCountTag: Sendable {}
public enum ServiceNameTag: Sendable {}
public enum ServiceVersionTag: Sendable {}
public enum ServiceInstanceIdentifierTag: Sendable {}
public enum DeploymentEnvironmentTag: Sendable {}
public enum ResourceAttributeNameTag: Sendable {}
public enum ResourceAttributeValueTag: Sendable {}
public enum MiddlewareNameTag: Sendable {}
public enum CircuitBreakerReasonTag: Sendable {}
public enum CircuitBreakerFailureThresholdTag: Sendable {}
public enum CircuitBreakerRecoveryTimeoutTag: Sendable {}
public enum CircuitBreakerSuccessThresholdTag: Sendable {}
public enum CircuitBreakerRollingWindowTag: Sendable {}
public enum CircuitBreakerFailureDecisionTag: Sendable {}
public enum CircuitBreakerFailureCountTag: Sendable {}
public enum ObservationDecisionTag: Sendable {}
public enum MetricsRecordLimitTag: Sendable {}
public enum TimingMetadataKeyTag: Sendable {}
public enum TimingMetadataValueTag: Sendable {}
public enum TraceFlagsTag: Sendable {}
public enum TraceSampledFlagTag: Sendable {}
public enum SpanEndedFlagTag: Sendable {}
public enum IncludeBodySizesFlagTag: Sendable {}
public enum RequestBodySizeTag: Sendable {}
public enum AuthenticationRequiredFlagTag: Sendable {}
public enum LoggingSubsystemNameTag: Sendable {}
public enum LoggingCategoryNameTag: Sendable {}
public enum LogBodyLengthLimitTag: Sendable {}

public typealias ObservabilityURLText = BoundaryString<ObservabilityURLTextTag>
public typealias ObservabilityHostName = BoundaryString<ObservabilityHostNameTag>
public typealias ObservabilityPathText = BoundaryString<ObservabilityPathTextTag>
public typealias ObservabilityBodySize = BoundaryInt<ObservabilityBodySizeTag>
public typealias ObservabilityUserAgent = BoundaryString<ObservabilityUserAgentTag>
public typealias CorrelationIdentifier = BoundaryString<CorrelationIdentifierTag>
public typealias SessionIdentifier = BoundaryString<SessionIdentifierTag>
public typealias UserIdentifier = BoundaryString<UserIdentifierTag>
public typealias DeviceIdentifier = BoundaryString<DeviceIdentifierTag>
public typealias AppVersionText = BoundaryString<AppVersionTextTag>
public typealias PlatformName = BoundaryString<PlatformNameTag>
public typealias NetworkTypeName = BoundaryString<NetworkTypeNameTag>
public typealias ObservabilityTagName = BoundaryString<ObservabilityTagNameTag>
public typealias ObservabilityTagValue = BoundaryString<ObservabilityTagValueTag>
public typealias StatusCategoryText = BoundaryString<StatusCategoryTextTag>
public typealias ResponseSize = BoundaryInt<ResponseSizeTag>
public typealias CompressionRatioValue = BoundaryDouble<CompressionRatioValueTag>
public typealias ErrorRateValue = BoundaryDouble<ErrorRateValueTag>
public typealias ThroughputValue = BoundaryDouble<ThroughputValueTag>
public typealias CacheHitRateValue = BoundaryDouble<CacheHitRateValueTag>
public typealias RetryRateValue = BoundaryDouble<RetryRateValueTag>
public typealias ActiveConnectionCount = BoundaryInt<ActiveConnectionCountTag>
public typealias RequestCount = BoundaryInt<RequestCountTag>
public typealias EndpointIdentifier = BoundaryString<EndpointIdentifierTag>
public typealias ObservabilityErrorType = BoundaryString<ObservabilityErrorTypeTag>
public typealias ObservabilityErrorCategory = BoundaryString<ObservabilityErrorCategoryTag>
public typealias UnderlyingErrorText = BoundaryString<UnderlyingErrorTextTag>
public typealias NetworkConditionText = BoundaryString<NetworkConditionTextTag>
public typealias ServerStatusText = BoundaryString<ServerStatusTextTag>
public typealias CollectHeadersFlag = BoundaryBool<CollectHeadersFlagTag>
public typealias CollectBodyInfoFlag = BoundaryBool<CollectBodyInfoFlagTag>
public typealias CollectDetailedMetricsFlag = BoundaryBool<CollectDetailedMetricsFlagTag>
public typealias MetricsCollectionDecision = BoundaryBool<MetricsCollectionDecisionTag>
public typealias ObservabilityDecision = BoundaryBool<ObservabilityDecisionTag>
public typealias EnableTracingFlag = BoundaryBool<EnableTracingFlagTag>
public typealias CollectBusinessMetricsFlag = BoundaryBool<CollectBusinessMetricsFlagTag>
public typealias TracingSampleRate = BoundaryDouble<TracingSampleRateTag>
public typealias MaxActiveTraceCount = BoundaryInt<MaxActiveTraceCountTag>
public typealias ActiveTraceCount = BoundaryInt<ActiveTraceCountTag>
public typealias MetricsReportingInterval = BoundaryDuration<MetricsReportingIntervalTag>
public typealias EnableRealtimeMetricsFlag = BoundaryBool<EnableRealtimeMetricsFlagTag>
public typealias MetricsRetentionDuration = BoundaryDuration<MetricsRetentionDurationTag>
public typealias RedactedHeaderName = BoundaryString<RedactedHeaderNameTag>
public typealias EventIdentifier = BoundaryUUID<EventIdentifierTag>
public typealias PersistenceDirectory = BoundaryURL<PersistenceDirectoryTag>
public typealias EnablePersistenceFlag = BoundaryBool<EnablePersistenceFlagTag>
public typealias EnableAlertingFlag = BoundaryBool<EnableAlertingFlagTag>
public typealias EventRetentionDuration = BoundaryDuration<EventRetentionDurationTag>
public typealias MetricsWindowSize = BoundaryDuration<MetricsWindowSizeTag>
public typealias MeasurementDuration = BoundaryDuration<MeasurementDurationTag>
public typealias MaxEventsInMemory = BoundaryInt<MaxEventsInMemoryTag>
public typealias DailyActiveUserCount = BoundaryInt<DailyActiveUserCountTag>
public typealias SessionCount = BoundaryInt<SessionCountTag>
public typealias ConversionRate = BoundaryDouble<ConversionRateTag>
public typealias UserRetentionRate = BoundaryDouble<UserRetentionRateTag>
public typealias AlertTitle = BoundaryString<AlertTitleTag>
public typealias AlertMessage = BoundaryString<AlertMessageTag>
public typealias AlertMetricName = BoundaryString<AlertMetricNameTag>
public typealias AlertThresholdValue = BoundaryDouble<AlertThresholdValueTag>
public typealias RequestSuccessFlag = BoundaryBool<RequestSuccessFlagTag>
public typealias MaxConcurrentTimingCount = BoundaryInt<MaxConcurrentTimingCountTag>
public typealias ActiveTimingCount = BoundaryInt<ActiveTimingCountTag>
public typealias ServiceName = BoundaryString<ServiceNameTag>
public typealias ServiceVersion = BoundaryString<ServiceVersionTag>
public typealias ServiceInstanceIdentifier = BoundaryString<ServiceInstanceIdentifierTag>
public typealias DeploymentEnvironmentName = BoundaryString<DeploymentEnvironmentTag>
public typealias ResourceAttributeName = BoundaryString<ResourceAttributeNameTag>
public typealias ResourceAttributeValue = BoundaryString<ResourceAttributeValueTag>
public typealias MiddlewareName = BoundaryString<MiddlewareNameTag>
public typealias CircuitBreakerReason = BoundaryString<CircuitBreakerReasonTag>
public typealias CircuitBreakerFailureThreshold = BoundaryInt<CircuitBreakerFailureThresholdTag>
public typealias CircuitBreakerRecoveryTimeout = BoundaryDuration<
  CircuitBreakerRecoveryTimeoutTag
>
public typealias CircuitBreakerSuccessThreshold = BoundaryInt<CircuitBreakerSuccessThresholdTag>
public typealias CircuitBreakerRollingWindow = BoundaryDuration<CircuitBreakerRollingWindowTag>
public typealias CircuitBreakerFailureDecision = BoundaryBool<CircuitBreakerFailureDecisionTag>
public typealias CircuitBreakerFailureCount = BoundaryInt<CircuitBreakerFailureCountTag>
public typealias ObservationDecision = BoundaryBool<ObservationDecisionTag>
public typealias MetricsRecordLimit = BoundaryInt<MetricsRecordLimitTag>
public typealias TimingMetadataKey = BoundaryString<TimingMetadataKeyTag>
public typealias TimingMetadataValue = BoundaryString<TimingMetadataValueTag>
public typealias TraceFlags = BoundaryInt<TraceFlagsTag>
public typealias TraceSampledFlag = BoundaryBool<TraceSampledFlagTag>
public typealias SpanEndedFlag = BoundaryBool<SpanEndedFlagTag>
public typealias IncludeBodySizesFlag = BoundaryBool<IncludeBodySizesFlagTag>
public typealias RequestBodySize = BoundaryInt<RequestBodySizeTag>
public typealias AuthenticationRequiredFlag = BoundaryBool<AuthenticationRequiredFlagTag>
public typealias LoggingSubsystemName = BoundaryString<LoggingSubsystemNameTag>
public typealias LoggingCategoryName = BoundaryString<LoggingCategoryNameTag>
public typealias LogBodyLengthLimit = BoundaryInt<LogBodyLengthLimitTag>
