import Foundation

public enum HeaderNameValidationFlagTag: Sendable {}
public enum HeaderValueValidationFlagTag: Sendable {}
public enum HeaderSanitizationFlagTag: Sendable {}
public enum HeaderValueLengthLimitTag: Sendable {}
public enum HeaderCountLimitTag: Sendable {}
public enum DangerousHeaderRemovalFlagTag: Sendable {}
public enum DangerousHeaderNameTag: Sendable {}
public enum HeaderValidationDecisionTag: Sendable {}
public enum CertificateHashTag: Sendable {}
public enum PinnedDomainTag: Sendable {}
public enum BackupCertificateAllowanceTag: Sendable {}
public enum PinnedKeyRequirementTag: Sendable {}
public enum TLSChainValidationFlagTag: Sendable {}
public enum TLSHostnameValidationFlagTag: Sendable {}
public enum CACertificateDataTag: Sendable {}
public enum ErrorContextMetadataKeyTag: Sendable {}
public enum ErrorContextMetadataValueTag: Sendable {}
public enum JitterFactorTag: Sendable {}
public enum TransferSpeedTextTag: Sendable {}
public enum TransferTimeRemainingTextTag: Sendable {}
public enum FileOperationDescriptionTag: Sendable {}
public enum TransferProgressSummaryTextTag: Sendable {}
public enum CacheExpirationFlagTag: Sendable {}
public enum CacheWarmSuccessFlagTag: Sendable {}
public enum CacheEntryCountTag: Sendable {}
public enum CachePrefetchDepthTag: Sendable {}
public enum CachePrefetchCountTag: Sendable {}
public enum AsyncSemaphorePermitCountTag: Sendable {}
public enum CacheEvictionDecisionTag: Sendable {}
public enum CacheExtensionOnAccessFlagTag: Sendable {}
public enum KeychainServiceNameTag: Sendable {}
public enum KeychainAccessGroupTag: Sendable {}
public enum KeychainSynchronizableFlagTag: Sendable {}
public enum KeychainItemKeyTag: Sendable {}
public enum KeychainStringValueTag: Sendable {}
public enum KeychainDataValueTag: Sendable {}
public enum KeychainItemExistenceFlagTag: Sendable {}
public enum OAuthClientIdentifierTag: Sendable {}
public enum KeychainStatusCodeTag: Sendable {}

public typealias HeaderNameValidationFlag = BoundaryBool<HeaderNameValidationFlagTag>
public typealias HeaderValueValidationFlag = BoundaryBool<HeaderValueValidationFlagTag>
public typealias HeaderSanitizationFlag = BoundaryBool<HeaderSanitizationFlagTag>
public typealias HeaderValueLengthLimit = BoundaryInt<HeaderValueLengthLimitTag>
public typealias HeaderCountLimit = BoundaryInt<HeaderCountLimitTag>
public typealias DangerousHeaderRemovalFlag = BoundaryBool<DangerousHeaderRemovalFlagTag>
public typealias DangerousHeaderName = BoundaryString<DangerousHeaderNameTag>
public typealias HeaderValidationDecision = BoundaryBool<HeaderValidationDecisionTag>
public typealias CertificateHash = BoundaryString<CertificateHashTag>
public typealias PinnedDomain = BoundaryString<PinnedDomainTag>
public typealias BackupCertificateAllowance = BoundaryBool<BackupCertificateAllowanceTag>
public typealias PinnedKeyRequirement = BoundaryBool<PinnedKeyRequirementTag>
public typealias TLSChainValidationFlag = BoundaryBool<TLSChainValidationFlagTag>
public typealias TLSHostnameValidationFlag = BoundaryBool<TLSHostnameValidationFlagTag>
public typealias CACertificateData = BoundaryData<CACertificateDataTag>
public typealias ErrorContextMetadataKey = BoundaryString<ErrorContextMetadataKeyTag>
public typealias ErrorContextMetadataValue = BoundaryString<ErrorContextMetadataValueTag>
public typealias JitterFactor = BoundaryDouble<JitterFactorTag>
public typealias TransferSpeedText = BoundaryString<TransferSpeedTextTag>
public typealias TransferTimeRemainingText = BoundaryString<TransferTimeRemainingTextTag>
public typealias FileOperationDescription = BoundaryString<FileOperationDescriptionTag>
public typealias TransferProgressSummaryText = BoundaryString<TransferProgressSummaryTextTag>
public typealias CacheExpirationFlag = BoundaryBool<CacheExpirationFlagTag>
public typealias CacheWarmSuccessFlag = BoundaryBool<CacheWarmSuccessFlagTag>
public typealias CacheEntryCount = BoundaryInt<CacheEntryCountTag>
public typealias CachePrefetchDepth = BoundaryInt<CachePrefetchDepthTag>
public typealias CachePrefetchCount = BoundaryInt<CachePrefetchCountTag>
public typealias AsyncSemaphorePermitCount = BoundaryInt<AsyncSemaphorePermitCountTag>
public typealias CacheEvictionDecision = BoundaryBool<CacheEvictionDecisionTag>
public typealias CacheExtensionOnAccessFlag = BoundaryBool<CacheExtensionOnAccessFlagTag>
public typealias KeychainServiceName = BoundaryString<KeychainServiceNameTag>
public typealias KeychainAccessGroup = BoundaryString<KeychainAccessGroupTag>
public typealias KeychainSynchronizableFlag = BoundaryBool<KeychainSynchronizableFlagTag>
public typealias KeychainItemKey = BoundaryString<KeychainItemKeyTag>
public typealias KeychainStringValue = BoundaryString<KeychainStringValueTag>
public typealias KeychainDataValue = BoundaryData<KeychainDataValueTag>
public typealias KeychainItemExistenceFlag = BoundaryBool<KeychainItemExistenceFlagTag>
public typealias OAuthClientIdentifier = BoundaryString<OAuthClientIdentifierTag>
public typealias KeychainStatusCode = BoundaryInt<KeychainStatusCodeTag>
