import Foundation

public enum BDDPhaseNameTag: Sendable {}
public enum BDDFeatureNameTag: Sendable {}
public enum BDDScenarioNameTag: Sendable {}
public enum BDDDescriptionTextTag: Sendable {}
public enum BDDStepKeywordTag: Sendable {}
public enum BDDStepTextTag: Sendable {}
public enum BDDStepPatternTag: Sendable {}
public enum BDDTagTextTag: Sendable {}
public enum BDDTagExpressionTag: Sendable {}
public enum BDDContextKeyNameTag: Sendable {}
public enum BDDDirectoryPathTag: Sendable {}
public enum BDDReportTitleTag: Sendable {}
public enum BDDFileURLTag: Sendable {}
public enum BDDSourceTextTag: Sendable {}
public enum BDDGenerateReportFlagTag: Sendable {}
public enum BDDStopOnFirstFailureFlagTag: Sendable {}
public enum BDDParallelExecutionFlagTag: Sendable {}
public enum BDDIdentifierTag: Sendable {}
public enum BDDExamplesNameTag: Sendable {}
public enum BDDExamplesHeaderTag: Sendable {}
public enum BDDExamplesCellTag: Sendable {}
public enum BDDDocContentTypeTag: Sendable {}
public enum BDDDocContentTag: Sendable {}
public enum BDDSourceLineTag: Sendable {}
public enum BDDSourceColumnTag: Sendable {}
public enum BDDSourceFilePathTag: Sendable {}
public enum BDDResultIdentifierTag: Sendable {}
public enum BDDScenarioCountTag: Sendable {}
public enum BDDScenarioCollectionNameTag: Sendable {}
public enum BDDStepCountTag: Sendable {}
public enum BDDTableColumnCountTag: Sendable {}
public enum BDDTableRowCountTag: Sendable {}
public enum BDDPassRateTag: Sendable {}
public enum BDDFailureMessageTag: Sendable {}
public enum BDDStepKeywordNameTag: Sendable {}
public enum BDDSemanticStepTypeNameTag: Sendable {}
public enum BDDResultStatusNameTag: Sendable {}

public enum BDDFilterMatchFlagTag: Sendable {}
public enum BDDDefinitionAvailabilityFlagTag: Sendable {}
public enum BDDPassedFlagTag: Sendable {}
public enum BDDFailedFlagTag: Sendable {}
public enum BDDStepCaptureTextTag: Sendable {}

public typealias BDDPhaseName = BoundaryString<BDDPhaseNameTag>
public typealias BDDFeatureName = BoundaryString<BDDFeatureNameTag>
public typealias BDDScenarioName = BoundaryString<BDDScenarioNameTag>
public typealias BDDDescriptionText = BoundaryString<BDDDescriptionTextTag>
public typealias BDDStepKeyword = BoundaryString<BDDStepKeywordTag>
public typealias BDDStepText = BoundaryString<BDDStepTextTag>
public typealias BDDStepPattern = BoundaryString<BDDStepPatternTag>
public typealias BDDTagText = BoundaryString<BDDTagTextTag>
public typealias BDDTagExpression = BoundaryString<BDDTagExpressionTag>
public typealias BDDContextKeyName = BoundaryString<BDDContextKeyNameTag>
public typealias BDDDirectoryPath = BoundaryString<BDDDirectoryPathTag>
public typealias BDDReportTitle = BoundaryString<BDDReportTitleTag>
public typealias BDDFileURL = BoundaryURL<BDDFileURLTag>
public typealias BDDSourceText = BoundaryString<BDDSourceTextTag>
public typealias BDDGenerateReportFlag = BoundaryBool<BDDGenerateReportFlagTag>
public typealias BDDStopOnFirstFailureFlag = BoundaryBool<BDDStopOnFirstFailureFlagTag>
public typealias BDDParallelExecutionFlag = BoundaryBool<BDDParallelExecutionFlagTag>
public typealias BDDIdentifier = BoundaryUUID<BDDIdentifierTag>
public typealias BDDExamplesName = BoundaryString<BDDExamplesNameTag>
public typealias BDDExamplesHeader = BoundaryString<BDDExamplesHeaderTag>
public typealias BDDExamplesCell = BoundaryString<BDDExamplesCellTag>
public typealias BDDDocContentType = BoundaryString<BDDDocContentTypeTag>
public typealias BDDDocContent = BoundaryString<BDDDocContentTag>
public typealias BDDSourceLine = BoundaryInt<BDDSourceLineTag>
public typealias BDDSourceColumn = BoundaryInt<BDDSourceColumnTag>
public typealias BDDSourceFilePath = BoundaryString<BDDSourceFilePathTag>
public typealias BDDResultIdentifier = BoundaryUUID<BDDResultIdentifierTag>
public typealias BDDScenarioCount = BoundaryInt<BDDScenarioCountTag>
public typealias BDDScenarioCollectionName = BoundaryString<BDDScenarioCollectionNameTag>
public typealias BDDStepCount = BoundaryInt<BDDStepCountTag>
public typealias BDDTableColumnCount = BoundaryInt<BDDTableColumnCountTag>
public typealias BDDTableRowCount = BoundaryInt<BDDTableRowCountTag>
public typealias BDDPassRate = BoundaryDouble<BDDPassRateTag>
public typealias BDDFailureMessage = BoundaryString<BDDFailureMessageTag>
public typealias BDDStepKeywordName = BoundaryString<BDDStepKeywordNameTag>
public typealias BDDSemanticStepTypeName = BoundaryString<BDDSemanticStepTypeNameTag>
public typealias BDDResultStatusName = BoundaryString<BDDResultStatusNameTag>

public typealias BDDFilterMatchFlag = BoundaryBool<BDDFilterMatchFlagTag>
public typealias BDDDefinitionAvailabilityFlag = BoundaryBool<BDDDefinitionAvailabilityFlagTag>
public typealias BDDPassedFlag = BoundaryBool<BDDPassedFlagTag>
public typealias BDDFailedFlag = BoundaryBool<BDDFailedFlagTag>
public typealias BDDStepCaptureText = BoundaryString<BDDStepCaptureTextTag>
