// swiftlint:disable file_length
import Foundation
public enum HTTPRequestIDTag: Sendable {}
public enum HTTPRequestURLTag: Sendable {}
public enum HTTPResponseURLTag: Sendable {}
public enum HTTPHeaderNameTag: Sendable {}
public enum HTTPHeaderValueTag: Sendable {}
public enum QueryParameterNameTag: Sendable {}
public enum QueryParameterValueTag: Sendable {}
public enum HTTPBodyTag: Sendable {}
public enum RequestTimeoutTag: Sendable {}
public enum HTTPMethodNameTag: Sendable {}
public enum HTTPStatusCodeTag: Sendable {}
public enum HTTPStatusInformationalFlagTag: Sendable {}
public enum HTTPStatusSuccessFlagTag: Sendable {}
public enum HTTPStatusRedirectionFlagTag: Sendable {}
public enum HTTPStatusClientErrorFlagTag: Sendable {}
public enum HTTPStatusServerErrorFlagTag: Sendable {}
public enum CacheKeyTag: Sendable {}
public enum CacheTagNameTag: Sendable {}
public enum CacheInvalidationPatternTag: Sendable {}
public enum CacheInvalidationFlagTag: Sendable {}
public enum RecoveryActionTitleTag: Sendable {}
public enum RecoveryActionDescriptionTag: Sendable {}
public enum RecoveryActionPrerequisiteTag: Sendable {}
public enum RecoveryActionAutomationFlagTag: Sendable {}
public enum UserActionNameTag: Sendable {}
public enum UserMessageTextTag: Sendable {}
public enum TechnicalSummaryTextTag: Sendable {}
public enum ActionAttemptCountTag: Sendable {}
public enum HTTPErrorMessageTag: Sendable {}
public enum HTTPErrorDetailTag: Sendable {}
public enum HTTPErrorTypeNameTag: Sendable {}
public enum HTTPErrorClientSideFlagTag: Sendable {}
public enum HTTPErrorServerSideFlagTag: Sendable {}
public enum HTTPErrorTransientFlagTag: Sendable {}
public enum EstimatedResolutionTimeTag: Sendable {}
public enum AutomaticResolutionFlagTag: Sendable {}
public enum ImpactLevelRankTag: Sendable {}
public enum ConfidenceLevelRankTag: Sendable {}
public enum BearerTokenValueTag: Sendable {}
public enum BasicAuthUsernameTag: Sendable {}
public enum BasicAuthPasswordTag: Sendable {}
public enum RetryAttemptCountTag: Sendable {}
public enum RetryDelayTag: Sendable {}
public enum RetryDecisionTag: Sendable {}
public enum BackoffMultiplierTag: Sendable {}
public enum CacheDecisionTag: Sendable {}
public enum CacheEntryLimitTag: Sendable {}
public enum CacheMaxAgeTag: Sendable {}
public enum CacheRevalidationFlagTag: Sendable {}
public enum CacheStoragePathTag: Sendable {}
public enum StorageSizeValueTag: Sendable {}
public enum SessionTimeoutTag: Sendable {}
public enum SessionAllowsCellularAccessTag: Sendable {}
public enum SessionAllowsExpensiveNetworkAccessTag: Sendable {}
public enum SessionAllowsConstrainedNetworkAccessTag: Sendable {}
public enum SessionWaitsForConnectivityTag: Sendable {}
public enum HostConnectionLimitTag: Sendable {}
public enum ConditionalRequestUsageTag: Sendable {}
public enum AuthenticationDecisionTag: Sendable {}
public enum AuthorizationTokenPrefixTag: Sendable {}
public enum BaseURLTextTag: Sendable {}
public enum RequestPathPatternTag: Sendable {}
public enum EndpointPathTag: Sendable {}
public enum HTTPMediaTypeTag: Sendable {}
public enum HTTPUserAgentValueTag: Sendable {}
public enum HTTPEnvironmentNameTag: Sendable {}
public enum HTTPResponseTextTag: Sendable {}
public enum HTTPBodyTextTag: Sendable {}
public enum HTTPTextEncodingTag: Sendable {}
public enum ParameterReferenceTag: Sendable {}
public enum MacroDiagnosticTextTag: Sendable {}
public enum MacroFunctionNameTag: Sendable {}
public enum MacroTypeReferenceTag: Sendable {}
public enum ValidationFlagTag: Sendable {}
public enum CacheHitFlagTag: Sendable {}
public enum CacheFreshnessFlagTag: Sendable {}
public enum CacheValidityFlagTag: Sendable {}
public enum CacheRevalidationRequiredFlagTag: Sendable {}
public enum DecoderNameTag: Sendable {}
public enum DecodedDataSizeTag: Sendable {}
public enum DecodingDurationTag: Sendable {}
public enum DecodingRateValueTag: Sendable {}
public enum CacheDirectiveTextTag: Sendable {}
public enum ImageDimensionValueTag: Sendable {}
public enum InterceptorMetadataKeyTag: Sendable {}
public enum MetadataTextValueTag: Sendable {}
public enum MetadataIntegerValueTag: Sendable {}
public enum MetadataDecimalValueTag: Sendable {}
public enum MetadataFlagTag: Sendable {}
public enum MetadataBinaryValueTag: Sendable {}
public enum RateLimitWindowDurationTag: Sendable {}
public enum RefreshTokenValueTag: Sendable {}
public enum InterceptorPresenceFlagTag: Sendable {}
public enum InterceptorCountTag: Sendable {}
public enum LoggingLevelRankTag: Sendable {}
public enum BDDPhaseNameTag: Sendable {}
public enum BDDFeatureNameTag: Sendable {}
public enum BDDScenarioNameTag: Sendable {}
public enum BDDDescriptionTextTag: Sendable {}
public enum BDDStepKeywordTag: Sendable {}
public enum BDDStepTextTag: Sendable {}
public enum BDDStepPatternTag: Sendable {}
public enum BDDTagTextTag: Sendable {}
public enum BDDTagExpressionTag: Sendable {}
public enum BDDContextKeyNameTag: Sendable {}
public enum BDDDirectoryPathTag: Sendable {}
public enum BDDReportTitleTag: Sendable {}
public enum BDDFileURLTag: Sendable {}
public enum BDDSourceTextTag: Sendable {}
public enum BDDGenerateReportFlagTag: Sendable {}
public enum BDDStopOnFirstFailureFlagTag: Sendable {}
public enum BDDParallelExecutionFlagTag: Sendable {}
public enum BDDIdentifierTag: Sendable {}
public enum BDDExamplesNameTag: Sendable {}
public enum BDDExamplesHeaderTag: Sendable {}
public enum BDDExamplesCellTag: Sendable {}
public enum BDDDocContentTypeTag: Sendable {}
public enum BDDDocContentTag: Sendable {}
public enum BDDSourceLineTag: Sendable {}
public enum BDDSourceColumnTag: Sendable {}
public enum BDDSourceFilePathTag: Sendable {}
public enum BDDResultIdentifierTag: Sendable {}
public enum BDDScenarioCountTag: Sendable {}
public enum BDDScenarioCollectionNameTag: Sendable {}
public enum BDDStepCountTag: Sendable {}
public enum BDDTableColumnCountTag: Sendable {}
public enum BDDTableRowCountTag: Sendable {}
public enum BDDPassRateTag: Sendable {}
public enum BDDFailureMessageTag: Sendable {}
public enum BDDStepKeywordNameTag: Sendable {}
public enum BDDSemanticStepTypeNameTag: Sendable {}
public enum BDDResultStatusNameTag: Sendable {}
public enum MockRequestPathTag: Sendable {}
public enum MockJSONResponseFlagTag: Sendable {}
public enum TraceVersionTag: Sendable {}
public enum TraceIdentifierTag: Sendable {}
public enum SpanIdentifierTag: Sendable {}
public enum TraceStateKeyTag: Sendable {}
public enum TraceStateValueTag: Sendable {}
public enum TraceSpanNameTag: Sendable {}
public enum TraceAttributeKeyTag: Sendable {}
public enum TraceAttributeValueTag: Sendable {}
public enum SpanEventNameTag: Sendable {}
public enum SpanStatusMessageTag: Sendable {}
public enum ObservabilityURLTextTag: Sendable {}
public enum ObservabilityHostNameTag: Sendable {}
public enum ObservabilityPathTextTag: Sendable {}
public enum ObservabilityBodySizeTag: Sendable {}
public enum ObservabilityUserAgentTag: Sendable {}
public enum CorrelationIdentifierTag: Sendable {}
public enum SessionIdentifierTag: Sendable {}
public enum UserIdentifierTag: Sendable {}
public enum DeviceIdentifierTag: Sendable {}
public enum AppVersionTextTag: Sendable {}
public enum PlatformNameTag: Sendable {}
public enum NetworkTypeNameTag: Sendable {}
public enum ObservabilityTagNameTag: Sendable {}
public enum ObservabilityTagValueTag: Sendable {}
public enum StatusCategoryTextTag: Sendable {}
public enum ResponseSizeTag: Sendable {}
public enum CompressionRatioValueTag: Sendable {}
public enum ErrorRateValueTag: Sendable {}
public enum ThroughputValueTag: Sendable {}
public enum CacheHitRateValueTag: Sendable {}
public enum RetryRateValueTag: Sendable {}
public enum ActiveConnectionCountTag: Sendable {}
public enum RequestCountTag: Sendable {}
public enum EndpointIdentifierTag: Sendable {}
public enum ObservabilityErrorTypeTag: Sendable {}
public enum ObservabilityErrorCategoryTag: Sendable {}
public enum UnderlyingErrorTextTag: Sendable {}
public enum NetworkConditionTextTag: Sendable {}
public enum ServerStatusTextTag: Sendable {}
public enum CollectHeadersFlagTag: Sendable {}
public enum CollectBodyInfoFlagTag: Sendable {}
public enum CollectDetailedMetricsFlagTag: Sendable {}
public enum MetricsCollectionDecisionTag: Sendable {}
public enum ObservabilityDecisionTag: Sendable {}
public enum EnableTracingFlagTag: Sendable {}
public enum CollectBusinessMetricsFlagTag: Sendable {}
public enum TracingSampleRateTag: Sendable {}
public enum MaxActiveTraceCountTag: Sendable {}
public enum ActiveTraceCountTag: Sendable {}
public enum MetricsReportingIntervalTag: Sendable {}
public enum EnableRealtimeMetricsFlagTag: Sendable {}
public enum MetricsRetentionDurationTag: Sendable {}
public enum RedactedHeaderNameTag: Sendable {}
public enum EventIdentifierTag: Sendable {}
public enum PersistenceDirectoryTag: Sendable {}
public enum EnablePersistenceFlagTag: Sendable {}
public enum EnableAlertingFlagTag: Sendable {}
public enum EventRetentionDurationTag: Sendable {}
public enum MetricsWindowSizeTag: Sendable {}
public enum MeasurementDurationTag: Sendable {}
public enum MaxEventsInMemoryTag: Sendable {}
public enum DailyActiveUserCountTag: Sendable {}
public enum SessionCountTag: Sendable {}
public enum ConversionRateTag: Sendable {}
public enum UserRetentionRateTag: Sendable {}
public enum AlertTitleTag: Sendable {}
public enum AlertMessageTag: Sendable {}
public enum AlertMetricNameTag: Sendable {}
public enum AlertThresholdValueTag: Sendable {}
public enum RequestSuccessFlagTag: Sendable {}
public enum MaxConcurrentTimingCountTag: Sendable {}
public enum ActiveTimingCountTag: Sendable {}
public enum ServiceNameTag: Sendable {}
public enum ServiceVersionTag: Sendable {}
public enum ServiceInstanceIdentifierTag: Sendable {}
public enum DeploymentEnvironmentTag: Sendable {}
public enum ResourceAttributeNameTag: Sendable {}
public enum ResourceAttributeValueTag: Sendable {}
public enum MiddlewareNameTag: Sendable {}
public enum CircuitBreakerReasonTag: Sendable {}
public enum CircuitBreakerFailureThresholdTag: Sendable {}
public enum CircuitBreakerRecoveryTimeoutTag: Sendable {}
public enum CircuitBreakerSuccessThresholdTag: Sendable {}
public enum CircuitBreakerRollingWindowTag: Sendable {}
public enum CircuitBreakerFailureDecisionTag: Sendable {}
public enum CircuitBreakerFailureCountTag: Sendable {}
public enum ObservationDecisionTag: Sendable {}
public enum MetricsRecordLimitTag: Sendable {}
public enum TimingMetadataKeyTag: Sendable {}
public enum TimingMetadataValueTag: Sendable {}
public enum TraceFlagsTag: Sendable {}
public enum TraceSampledFlagTag: Sendable {}
public enum SpanEndedFlagTag: Sendable {}
public enum IncludeBodySizesFlagTag: Sendable {}
public enum RequestBodySizeTag: Sendable {}
public enum AuthenticationRequiredFlagTag: Sendable {}
public enum LoggingSubsystemNameTag: Sendable {}
public enum LoggingCategoryNameTag: Sendable {}
public enum LogBodyLengthLimitTag: Sendable {}
public enum BatchConcurrencyLimitTag: Sendable {}
public enum BatchRequestIndexTag: Sendable {}
public enum CancelOnFailureFlagTag: Sendable {}
public enum TransferIdentifierTag: Sendable {}
public enum TransferByteCountTag: Sendable {}
public enum TransferDurationTag: Sendable {}
public enum TransferSpeedTag: Sendable {}
public enum TransferSuccessFlagTag: Sendable {}
public enum TransferResumeDataTag: Sendable {}
public enum FileNameTag: Sendable {}
public enum FileSizeTag: Sendable {}
public enum FileChecksumTag: Sendable {}
public enum FileSystemPathTag: Sendable {}
public enum TemporaryDirectoryTag: Sendable {}
public enum ChecksumAlgorithmNameTag: Sendable {}
public enum BackgroundSessionIdentifierTag: Sendable {}
public enum FileIntegrityCheckFlagTag: Sendable {}
public enum ResumableTransferFlagTag: Sendable {}
public enum BackgroundTransferFlagTag: Sendable {}
public enum LocalFileURLTag: Sendable {}
public enum RemoteTransferURLTag: Sendable {}
public enum FileExtensionTag: Sendable {}
public enum TransferByteRateTag: Sendable {}
public enum TransferTimeWindowTag: Sendable {}
public enum TransferConcurrencyLimitTag: Sendable {}
public enum AdaptivePriorityFlagTag: Sendable {}
public enum TransferRetryCountTag: Sendable {}
public enum TransferPauseCountTag: Sendable {}
public enum TransferResumeCountTag: Sendable {}
public enum TransferEfficiencyValueTag: Sendable {}
public enum TransferCountTag: Sendable {}
public enum TransferSuccessRateTag: Sendable {}
public enum TransferProgressFractionTag: Sendable {}
public enum TransferOffsetTag: Sendable {}
public enum ChunkSizeTag: Sendable {}
public enum ChunkCountTag: Sendable {}
public enum UploadProgressTrackingFlagTag: Sendable {}
public enum DownloadProgressTrackingFlagTag: Sendable {}
public enum ChunkedTransferSupportFlagTag: Sendable {}
public enum TransferActivityFlagTag: Sendable {}
public enum TransferPauseCapabilityFlagTag: Sendable {}
public enum TransferResumeCapabilityFlagTag: Sendable {}
public enum TransferCancelCapabilityFlagTag: Sendable {}
public enum TransferAllowanceFlagTag: Sendable {}
public enum TransferStateNameTag: Sendable {}
public enum TransferControlActionNameTag: Sendable {}
public enum TransferPriorityRankTag: Sendable {}
public enum TransferDirectionNameTag: Sendable {}
public enum CacheEntryAgeTag: Sendable {}
public enum CachePatternNameTag: Sendable {}
public enum CachePreloadPriorityTag: Sendable {}
public enum CachePreloadConcurrencyTag: Sendable {}
public enum StorageSizeBytesTag: Sendable {}
public enum CacheHitCountTag: Sendable {}
public enum CacheMissCountTag: Sendable {}
public enum CacheEvictionCountTag: Sendable {}
public enum CacheHitRatioMetricTag: Sendable {}
public enum CacheDirectoryURLTag: Sendable {}
public enum CompressionEnabledFlagTag: Sendable {}
public enum CacheExtensionFactorTag: Sendable {}
public enum HeaderNameValidationFlagTag: Sendable {}
public enum HeaderValueValidationFlagTag: Sendable {}
public enum HeaderSanitizationFlagTag: Sendable {}
public enum HeaderValueLengthLimitTag: Sendable {}
public enum HeaderCountLimitTag: Sendable {}
public enum DangerousHeaderRemovalFlagTag: Sendable {}
public enum DangerousHeaderNameTag: Sendable {}
public enum HeaderValidationDecisionTag: Sendable {}
public enum CertificateHashTag: Sendable {}
public enum PinnedDomainTag: Sendable {}
public enum BackupCertificateAllowanceTag: Sendable {}
public enum PinnedKeyRequirementTag: Sendable {}
public enum TLSChainValidationFlagTag: Sendable {}
public enum TLSHostnameValidationFlagTag: Sendable {}
public enum CACertificateDataTag: Sendable {}
public enum ErrorContextMetadataKeyTag: Sendable {}
public enum ErrorContextMetadataValueTag: Sendable {}
public enum JitterFactorTag: Sendable {}
public enum TransferSpeedTextTag: Sendable {}
public enum TransferTimeRemainingTextTag: Sendable {}
public enum FileOperationDescriptionTag: Sendable {}
public enum TransferProgressSummaryTextTag: Sendable {}
public enum CacheExpirationFlagTag: Sendable {}
public enum CacheWarmSuccessFlagTag: Sendable {}
public enum CacheEntryCountTag: Sendable {}
public enum CachePrefetchDepthTag: Sendable {}
public enum CachePrefetchCountTag: Sendable {}
public enum AsyncSemaphorePermitCountTag: Sendable {}
public enum CacheEvictionDecisionTag: Sendable {}
public enum CacheExtensionOnAccessFlagTag: Sendable {}
public enum KeychainServiceNameTag: Sendable {}
public enum KeychainAccessGroupTag: Sendable {}
public enum KeychainSynchronizableFlagTag: Sendable {}
public enum KeychainItemKeyTag: Sendable {}
public enum KeychainStringValueTag: Sendable {}
public enum KeychainDataValueTag: Sendable {}
public enum KeychainItemExistenceFlagTag: Sendable {}
public enum OAuthClientIdentifierTag: Sendable {}
public enum KeychainStatusCodeTag: Sendable {}
public enum RequestRecordingEnabledFlagTag: Sendable {}
public enum MockVerificationCountTag: Sendable {}
public enum MockUnixTimestampTag: Sendable {}
public enum MockTimeAdjustmentTag: Sendable {}
public enum MockRequestIndexTag: Sendable {}
public enum MockResponseIndexTag: Sendable {}
public enum MockContextIdentifierTag: Sendable {}
public enum MockURLPatternTag: Sendable {}
public enum MockPredicateMatchFlagTag: Sendable {}
public enum MockResponseDelayTag: Sendable {}
public enum ExpectationDescriptionTextTag: Sendable {}
public enum ExpectationFulfillmentFlagTag: Sendable {}
public enum TestingSupportEnabledFlagTag: Sendable {}
public enum TestingToolNameTag: Sendable {}
public enum TestingUtilitiesVersionTag: Sendable {}
public enum BDDFilterMatchFlagTag: Sendable {}
public enum BDDDefinitionAvailabilityFlagTag: Sendable {}
public enum BDDPassedFlagTag: Sendable {}
public enum BDDFailedFlagTag: Sendable {}
public enum BDDStepCaptureTextTag: Sendable {}

public typealias HTTPRequestID = BoundaryUUID<HTTPRequestIDTag>
public typealias HTTPRequestURL = BoundaryURL<HTTPRequestURLTag>
public typealias HTTPResponseURL = BoundaryURL<HTTPResponseURLTag>
public typealias HTTPHeaderName = BoundaryString<HTTPHeaderNameTag>
public typealias HTTPHeaderValue = BoundaryString<HTTPHeaderValueTag>
public typealias QueryParameterName = BoundaryString<QueryParameterNameTag>
public typealias QueryParameterValue = BoundaryString<QueryParameterValueTag>
public typealias HTTPBody = BoundaryData<HTTPBodyTag>
public typealias RequestTimeout = BoundaryDuration<RequestTimeoutTag>
public typealias HTTPMethodName = BoundaryString<HTTPMethodNameTag>
public typealias HTTPStatusCode = BoundaryInt<HTTPStatusCodeTag>
public typealias HTTPStatusInformationalFlag = BoundaryBool<HTTPStatusInformationalFlagTag>
public typealias HTTPStatusSuccessFlag = BoundaryBool<HTTPStatusSuccessFlagTag>
public typealias HTTPStatusRedirectionFlag = BoundaryBool<HTTPStatusRedirectionFlagTag>
public typealias HTTPStatusClientErrorFlag = BoundaryBool<HTTPStatusClientErrorFlagTag>
public typealias HTTPStatusServerErrorFlag = BoundaryBool<HTTPStatusServerErrorFlagTag>
public typealias CacheKey = BoundaryString<CacheKeyTag>
public typealias CacheTagName = BoundaryString<CacheTagNameTag>
public typealias CacheInvalidationPattern = BoundaryString<CacheInvalidationPatternTag>
public typealias CacheInvalidationFlag = BoundaryBool<CacheInvalidationFlagTag>
public typealias RecoveryActionTitle = BoundaryString<RecoveryActionTitleTag>
public typealias RecoveryActionDescription = BoundaryString<RecoveryActionDescriptionTag>
public typealias RecoveryActionPrerequisite = BoundaryString<RecoveryActionPrerequisiteTag>
public typealias RecoveryActionAutomationFlag = BoundaryBool<RecoveryActionAutomationFlagTag>
public typealias UserActionName = BoundaryString<UserActionNameTag>
public typealias UserMessageText = BoundaryString<UserMessageTextTag>
public typealias TechnicalSummaryText = BoundaryString<TechnicalSummaryTextTag>
public typealias ActionAttemptCount = BoundaryInt<ActionAttemptCountTag>
public typealias HTTPErrorMessage = BoundaryString<HTTPErrorMessageTag>
public typealias HTTPErrorDetail = BoundaryString<HTTPErrorDetailTag>
public typealias HTTPErrorTypeName = BoundaryString<HTTPErrorTypeNameTag>
public typealias HTTPErrorClientSideFlag = BoundaryBool<HTTPErrorClientSideFlagTag>
public typealias HTTPErrorServerSideFlag = BoundaryBool<HTTPErrorServerSideFlagTag>
public typealias HTTPErrorTransientFlag = BoundaryBool<HTTPErrorTransientFlagTag>
public typealias EstimatedResolutionTime = BoundaryDuration<EstimatedResolutionTimeTag>
public typealias AutomaticResolutionFlag = BoundaryBool<AutomaticResolutionFlagTag>
public typealias ImpactLevelRank = BoundaryInt<ImpactLevelRankTag>
public typealias ConfidenceLevelRank = BoundaryInt<ConfidenceLevelRankTag>
public typealias BearerTokenValue = BoundaryString<BearerTokenValueTag>
public typealias BasicAuthUsername = BoundaryString<BasicAuthUsernameTag>
public typealias BasicAuthPassword = BoundaryString<BasicAuthPasswordTag>
public typealias RetryAttemptCount = BoundaryInt<RetryAttemptCountTag>
public typealias RetryDelay = BoundaryDuration<RetryDelayTag>
public typealias RetryDecision = BoundaryBool<RetryDecisionTag>
public typealias BackoffMultiplier = BoundaryDouble<BackoffMultiplierTag>
public typealias CacheDecision = BoundaryBool<CacheDecisionTag>
public typealias CacheEntryLimit = BoundaryInt<CacheEntryLimitTag>
public typealias CacheMaxAge = BoundaryDuration<CacheMaxAgeTag>
public typealias CacheRevalidationFlag = BoundaryBool<CacheRevalidationFlagTag>
public typealias CacheStoragePath = BoundaryString<CacheStoragePathTag>
public typealias StorageSizeValue = BoundaryInt<StorageSizeValueTag>
public typealias SessionRequestTimeout = BoundaryDuration<SessionTimeoutTag>
public typealias SessionAllowsCellularAccess = BoundaryBool<SessionAllowsCellularAccessTag>
public typealias SessionAllowsExpensiveNetworkAccess = BoundaryBool<
  SessionAllowsExpensiveNetworkAccessTag
>
public typealias SessionAllowsConstrainedNetworkAccess = BoundaryBool<
  SessionAllowsConstrainedNetworkAccessTag
>
public typealias SessionWaitsForConnectivity = BoundaryBool<SessionWaitsForConnectivityTag>
public typealias HostConnectionLimit = BoundaryInt<HostConnectionLimitTag>
public typealias ConditionalRequestUsage = BoundaryBool<ConditionalRequestUsageTag>
public typealias AuthenticationDecision = BoundaryBool<AuthenticationDecisionTag>
public typealias AuthorizationTokenPrefix = BoundaryString<AuthorizationTokenPrefixTag>
public typealias BaseURLText = BoundaryString<BaseURLTextTag>
public typealias RequestPathPattern = BoundaryString<RequestPathPatternTag>
public typealias EndpointPath = BoundaryString<EndpointPathTag>
public typealias HTTPMediaType = BoundaryString<HTTPMediaTypeTag>
public typealias HTTPUserAgentValue = BoundaryString<HTTPUserAgentValueTag>
public typealias HTTPEnvironmentName = BoundaryString<HTTPEnvironmentNameTag>
public typealias HTTPResponseText = BoundaryString<HTTPResponseTextTag>
public typealias HTTPBodyText = BoundaryString<HTTPBodyTextTag>
public typealias HTTPTextEncoding = BoundaryString<HTTPTextEncodingTag>
public typealias ParameterReference = BoundaryString<ParameterReferenceTag>
public typealias MacroDiagnosticText = BoundaryString<MacroDiagnosticTextTag>
public typealias MacroFunctionName = BoundaryString<MacroFunctionNameTag>
public typealias MacroTypeReference = BoundaryString<MacroTypeReferenceTag>
public typealias ValidationFlag = BoundaryBool<ValidationFlagTag>
public typealias CacheHitFlag = BoundaryBool<CacheHitFlagTag>
public typealias CacheFreshnessFlag = BoundaryBool<CacheFreshnessFlagTag>
public typealias CacheValidityFlag = BoundaryBool<CacheValidityFlagTag>
public typealias CacheRevalidationRequiredFlag = BoundaryBool<CacheRevalidationRequiredFlagTag>
public typealias DecoderName = BoundaryString<DecoderNameTag>
public typealias DecodedDataSize = BoundaryInt<DecodedDataSizeTag>
public typealias DecodingDuration = BoundaryDuration<DecodingDurationTag>
public typealias DecodingRateValue = BoundaryDouble<DecodingRateValueTag>
public typealias CacheDirectiveText = BoundaryString<CacheDirectiveTextTag>
public typealias ImageDimensionValue = BoundaryDouble<ImageDimensionValueTag>
public typealias InterceptorMetadataKey = BoundaryString<InterceptorMetadataKeyTag>
public typealias MetadataTextValue = BoundaryString<MetadataTextValueTag>
public typealias MetadataIntegerValue = BoundaryInt<MetadataIntegerValueTag>
public typealias MetadataDecimalValue = BoundaryDouble<MetadataDecimalValueTag>
public typealias MetadataFlag = BoundaryBool<MetadataFlagTag>
public typealias MetadataBinaryValue = BoundaryData<MetadataBinaryValueTag>
public typealias RateLimitWindowDuration = BoundaryDuration<RateLimitWindowDurationTag>
public typealias RefreshTokenValue = BoundaryString<RefreshTokenValueTag>
public typealias InterceptorPresenceFlag = BoundaryBool<InterceptorPresenceFlagTag>
public typealias InterceptorCount = BoundaryInt<InterceptorCountTag>
public typealias LoggingLevelRank = BoundaryInt<LoggingLevelRankTag>
public typealias BDDPhaseName = BoundaryString<BDDPhaseNameTag>
public typealias BDDFeatureName = BoundaryString<BDDFeatureNameTag>
public typealias BDDScenarioName = BoundaryString<BDDScenarioNameTag>
public typealias BDDDescriptionText = BoundaryString<BDDDescriptionTextTag>
public typealias BDDStepKeyword = BoundaryString<BDDStepKeywordTag>
public typealias BDDStepText = BoundaryString<BDDStepTextTag>
public typealias BDDStepPattern = BoundaryString<BDDStepPatternTag>
public typealias BDDTagText = BoundaryString<BDDTagTextTag>
public typealias BDDTagExpression = BoundaryString<BDDTagExpressionTag>
public typealias BDDContextKeyName = BoundaryString<BDDContextKeyNameTag>
public typealias BDDDirectoryPath = BoundaryString<BDDDirectoryPathTag>
public typealias BDDReportTitle = BoundaryString<BDDReportTitleTag>
public typealias BDDFileURL = BoundaryURL<BDDFileURLTag>
public typealias BDDSourceText = BoundaryString<BDDSourceTextTag>
public typealias BDDGenerateReportFlag = BoundaryBool<BDDGenerateReportFlagTag>
public typealias BDDStopOnFirstFailureFlag = BoundaryBool<BDDStopOnFirstFailureFlagTag>
public typealias BDDParallelExecutionFlag = BoundaryBool<BDDParallelExecutionFlagTag>
public typealias BDDIdentifier = BoundaryUUID<BDDIdentifierTag>
public typealias BDDExamplesName = BoundaryString<BDDExamplesNameTag>
public typealias BDDExamplesHeader = BoundaryString<BDDExamplesHeaderTag>
public typealias BDDExamplesCell = BoundaryString<BDDExamplesCellTag>
public typealias BDDDocContentType = BoundaryString<BDDDocContentTypeTag>
public typealias BDDDocContent = BoundaryString<BDDDocContentTag>
public typealias BDDSourceLine = BoundaryInt<BDDSourceLineTag>
public typealias BDDSourceColumn = BoundaryInt<BDDSourceColumnTag>
public typealias BDDSourceFilePath = BoundaryString<BDDSourceFilePathTag>
public typealias BDDResultIdentifier = BoundaryUUID<BDDResultIdentifierTag>
public typealias BDDScenarioCount = BoundaryInt<BDDScenarioCountTag>
public typealias BDDScenarioCollectionName = BoundaryString<BDDScenarioCollectionNameTag>
public typealias BDDStepCount = BoundaryInt<BDDStepCountTag>
public typealias BDDTableColumnCount = BoundaryInt<BDDTableColumnCountTag>
public typealias BDDTableRowCount = BoundaryInt<BDDTableRowCountTag>
public typealias BDDPassRate = BoundaryDouble<BDDPassRateTag>
public typealias BDDFailureMessage = BoundaryString<BDDFailureMessageTag>
public typealias BDDStepKeywordName = BoundaryString<BDDStepKeywordNameTag>
public typealias BDDSemanticStepTypeName = BoundaryString<BDDSemanticStepTypeNameTag>
public typealias BDDResultStatusName = BoundaryString<BDDResultStatusNameTag>
public typealias MockRequestPath = BoundaryString<MockRequestPathTag>
public typealias MockJSONResponseFlag = BoundaryBool<MockJSONResponseFlagTag>
public typealias TraceVersion = BoundaryString<TraceVersionTag>
public typealias TraceIdentifier = BoundaryString<TraceIdentifierTag>
public typealias SpanIdentifier = BoundaryString<SpanIdentifierTag>
public typealias TraceStateKey = BoundaryString<TraceStateKeyTag>
public typealias TraceStateValue = BoundaryString<TraceStateValueTag>
public typealias TraceSpanName = BoundaryString<TraceSpanNameTag>
public typealias TraceAttributeKey = BoundaryString<TraceAttributeKeyTag>
public typealias TraceAttributeValue = BoundaryString<TraceAttributeValueTag>
public typealias SpanEventName = BoundaryString<SpanEventNameTag>
public typealias SpanStatusMessage = BoundaryString<SpanStatusMessageTag>
public typealias ObservabilityURLText = BoundaryString<ObservabilityURLTextTag>
public typealias ObservabilityHostName = BoundaryString<ObservabilityHostNameTag>
public typealias ObservabilityPathText = BoundaryString<ObservabilityPathTextTag>
public typealias ObservabilityBodySize = BoundaryInt<ObservabilityBodySizeTag>
public typealias ObservabilityUserAgent = BoundaryString<ObservabilityUserAgentTag>
public typealias CorrelationIdentifier = BoundaryString<CorrelationIdentifierTag>
public typealias SessionIdentifier = BoundaryString<SessionIdentifierTag>
public typealias UserIdentifier = BoundaryString<UserIdentifierTag>
public typealias DeviceIdentifier = BoundaryString<DeviceIdentifierTag>
public typealias AppVersionText = BoundaryString<AppVersionTextTag>
public typealias PlatformName = BoundaryString<PlatformNameTag>
public typealias NetworkTypeName = BoundaryString<NetworkTypeNameTag>
public typealias ObservabilityTagName = BoundaryString<ObservabilityTagNameTag>
public typealias ObservabilityTagValue = BoundaryString<ObservabilityTagValueTag>
public typealias StatusCategoryText = BoundaryString<StatusCategoryTextTag>
public typealias ResponseSize = BoundaryInt<ResponseSizeTag>
public typealias CompressionRatioValue = BoundaryDouble<CompressionRatioValueTag>
public typealias ErrorRateValue = BoundaryDouble<ErrorRateValueTag>
public typealias ThroughputValue = BoundaryDouble<ThroughputValueTag>
public typealias CacheHitRateValue = BoundaryDouble<CacheHitRateValueTag>
public typealias RetryRateValue = BoundaryDouble<RetryRateValueTag>
public typealias ActiveConnectionCount = BoundaryInt<ActiveConnectionCountTag>
public typealias RequestCount = BoundaryInt<RequestCountTag>
public typealias EndpointIdentifier = BoundaryString<EndpointIdentifierTag>
public typealias ObservabilityErrorType = BoundaryString<ObservabilityErrorTypeTag>
public typealias ObservabilityErrorCategory = BoundaryString<ObservabilityErrorCategoryTag>
public typealias UnderlyingErrorText = BoundaryString<UnderlyingErrorTextTag>
public typealias NetworkConditionText = BoundaryString<NetworkConditionTextTag>
public typealias ServerStatusText = BoundaryString<ServerStatusTextTag>
public typealias CollectHeadersFlag = BoundaryBool<CollectHeadersFlagTag>
public typealias CollectBodyInfoFlag = BoundaryBool<CollectBodyInfoFlagTag>
public typealias CollectDetailedMetricsFlag = BoundaryBool<CollectDetailedMetricsFlagTag>
public typealias MetricsCollectionDecision = BoundaryBool<MetricsCollectionDecisionTag>
public typealias ObservabilityDecision = BoundaryBool<ObservabilityDecisionTag>
public typealias EnableTracingFlag = BoundaryBool<EnableTracingFlagTag>
public typealias CollectBusinessMetricsFlag = BoundaryBool<CollectBusinessMetricsFlagTag>
public typealias TracingSampleRate = BoundaryDouble<TracingSampleRateTag>
public typealias MaxActiveTraceCount = BoundaryInt<MaxActiveTraceCountTag>
public typealias ActiveTraceCount = BoundaryInt<ActiveTraceCountTag>
public typealias MetricsReportingInterval = BoundaryDuration<MetricsReportingIntervalTag>
public typealias EnableRealtimeMetricsFlag = BoundaryBool<EnableRealtimeMetricsFlagTag>
public typealias MetricsRetentionDuration = BoundaryDuration<MetricsRetentionDurationTag>
public typealias RedactedHeaderName = BoundaryString<RedactedHeaderNameTag>
public typealias EventIdentifier = BoundaryUUID<EventIdentifierTag>
public typealias PersistenceDirectory = BoundaryURL<PersistenceDirectoryTag>
public typealias EnablePersistenceFlag = BoundaryBool<EnablePersistenceFlagTag>
public typealias EnableAlertingFlag = BoundaryBool<EnableAlertingFlagTag>
public typealias EventRetentionDuration = BoundaryDuration<EventRetentionDurationTag>
public typealias MetricsWindowSize = BoundaryDuration<MetricsWindowSizeTag>
public typealias MeasurementDuration = BoundaryDuration<MeasurementDurationTag>
public typealias MaxEventsInMemory = BoundaryInt<MaxEventsInMemoryTag>
public typealias DailyActiveUserCount = BoundaryInt<DailyActiveUserCountTag>
public typealias SessionCount = BoundaryInt<SessionCountTag>
public typealias ConversionRate = BoundaryDouble<ConversionRateTag>
public typealias UserRetentionRate = BoundaryDouble<UserRetentionRateTag>
public typealias AlertTitle = BoundaryString<AlertTitleTag>
public typealias AlertMessage = BoundaryString<AlertMessageTag>
public typealias AlertMetricName = BoundaryString<AlertMetricNameTag>
public typealias AlertThresholdValue = BoundaryDouble<AlertThresholdValueTag>
public typealias RequestSuccessFlag = BoundaryBool<RequestSuccessFlagTag>
public typealias MaxConcurrentTimingCount = BoundaryInt<MaxConcurrentTimingCountTag>
public typealias ActiveTimingCount = BoundaryInt<ActiveTimingCountTag>
public typealias ServiceName = BoundaryString<ServiceNameTag>
public typealias ServiceVersion = BoundaryString<ServiceVersionTag>
public typealias ServiceInstanceIdentifier = BoundaryString<ServiceInstanceIdentifierTag>
public typealias DeploymentEnvironmentName = BoundaryString<DeploymentEnvironmentTag>
public typealias ResourceAttributeName = BoundaryString<ResourceAttributeNameTag>
public typealias ResourceAttributeValue = BoundaryString<ResourceAttributeValueTag>
public typealias MiddlewareName = BoundaryString<MiddlewareNameTag>
public typealias CircuitBreakerReason = BoundaryString<CircuitBreakerReasonTag>
public typealias CircuitBreakerFailureThreshold = BoundaryInt<CircuitBreakerFailureThresholdTag>
public typealias CircuitBreakerRecoveryTimeout = BoundaryDuration<
  CircuitBreakerRecoveryTimeoutTag
>
public typealias CircuitBreakerSuccessThreshold = BoundaryInt<CircuitBreakerSuccessThresholdTag>
public typealias CircuitBreakerRollingWindow = BoundaryDuration<CircuitBreakerRollingWindowTag>
public typealias CircuitBreakerFailureDecision = BoundaryBool<CircuitBreakerFailureDecisionTag>
public typealias CircuitBreakerFailureCount = BoundaryInt<CircuitBreakerFailureCountTag>
public typealias ObservationDecision = BoundaryBool<ObservationDecisionTag>
public typealias MetricsRecordLimit = BoundaryInt<MetricsRecordLimitTag>
public typealias TimingMetadataKey = BoundaryString<TimingMetadataKeyTag>
public typealias TimingMetadataValue = BoundaryString<TimingMetadataValueTag>
public typealias TraceFlags = BoundaryInt<TraceFlagsTag>
public typealias TraceSampledFlag = BoundaryBool<TraceSampledFlagTag>
public typealias SpanEndedFlag = BoundaryBool<SpanEndedFlagTag>
public typealias IncludeBodySizesFlag = BoundaryBool<IncludeBodySizesFlagTag>
public typealias RequestBodySize = BoundaryInt<RequestBodySizeTag>
public typealias AuthenticationRequiredFlag = BoundaryBool<AuthenticationRequiredFlagTag>
public typealias LoggingSubsystemName = BoundaryString<LoggingSubsystemNameTag>
public typealias LoggingCategoryName = BoundaryString<LoggingCategoryNameTag>
public typealias LogBodyLengthLimit = BoundaryInt<LogBodyLengthLimitTag>
public typealias BatchConcurrencyLimit = BoundaryInt<BatchConcurrencyLimitTag>
public typealias BatchRequestIndex = BoundaryInt<BatchRequestIndexTag>
public typealias CancelOnFailureFlag = BoundaryBool<CancelOnFailureFlagTag>
public typealias TransferIdentifier = BoundaryUUID<TransferIdentifierTag>
public typealias TransferByteCount = BoundaryInt64<TransferByteCountTag>
public typealias TransferDuration = BoundaryDuration<TransferDurationTag>
public typealias TransferSpeed = BoundaryDouble<TransferSpeedTag>
public typealias TransferSuccessFlag = BoundaryBool<TransferSuccessFlagTag>
public typealias TransferResumeData = BoundaryData<TransferResumeDataTag>
public typealias FileName = BoundaryString<FileNameTag>
public typealias FileSize = BoundaryInt64<FileSizeTag>
public typealias FileChecksum = BoundaryString<FileChecksumTag>
public typealias FileSystemPath = BoundaryString<FileSystemPathTag>
public typealias TemporaryDirectoryURL = BoundaryURL<TemporaryDirectoryTag>
public typealias ChecksumAlgorithmName = BoundaryString<ChecksumAlgorithmNameTag>
public typealias BackgroundSessionIdentifier = BoundaryString<BackgroundSessionIdentifierTag>
public typealias FileIntegrityCheckFlag = BoundaryBool<FileIntegrityCheckFlagTag>
public typealias ResumableTransferFlag = BoundaryBool<ResumableTransferFlagTag>
public typealias BackgroundTransferFlag = BoundaryBool<BackgroundTransferFlagTag>
public typealias LocalFileURL = BoundaryURL<LocalFileURLTag>
public typealias RemoteTransferURL = BoundaryURL<RemoteTransferURLTag>
public typealias FileExtension = BoundaryString<FileExtensionTag>
public typealias TransferByteRate = BoundaryDouble<TransferByteRateTag>
public typealias TransferTimeWindow = BoundaryDuration<TransferTimeWindowTag>
public typealias TransferConcurrencyLimit = BoundaryInt<TransferConcurrencyLimitTag>
public typealias AdaptivePriorityFlag = BoundaryBool<AdaptivePriorityFlagTag>
public typealias TransferRetryCount = BoundaryInt<TransferRetryCountTag>
public typealias TransferPauseCount = BoundaryInt<TransferPauseCountTag>
public typealias TransferResumeCount = BoundaryInt<TransferResumeCountTag>
public typealias TransferEfficiencyValue = BoundaryDouble<TransferEfficiencyValueTag>
public typealias TransferCount = BoundaryInt<TransferCountTag>
public typealias TransferSuccessRate = BoundaryDouble<TransferSuccessRateTag>
public typealias TransferProgressFraction = BoundaryDouble<TransferProgressFractionTag>
public typealias TransferOffset = BoundaryInt64<TransferOffsetTag>
public typealias ChunkSize = BoundaryInt64<ChunkSizeTag>
public typealias ChunkCount = BoundaryInt<ChunkCountTag>
public typealias UploadProgressTrackingFlag = BoundaryBool<UploadProgressTrackingFlagTag>
public typealias DownloadProgressTrackingFlag = BoundaryBool<DownloadProgressTrackingFlagTag>
public typealias ChunkedTransferSupportFlag = BoundaryBool<ChunkedTransferSupportFlagTag>
public typealias TransferActivityFlag = BoundaryBool<TransferActivityFlagTag>
public typealias TransferPauseCapabilityFlag = BoundaryBool<TransferPauseCapabilityFlagTag>
public typealias TransferResumeCapabilityFlag = BoundaryBool<TransferResumeCapabilityFlagTag>
public typealias TransferCancelCapabilityFlag = BoundaryBool<TransferCancelCapabilityFlagTag>
public typealias TransferAllowanceFlag = BoundaryBool<TransferAllowanceFlagTag>
public typealias TransferStateName = BoundaryString<TransferStateNameTag>
public typealias TransferControlActionName = BoundaryString<TransferControlActionNameTag>
public typealias TransferPriorityRank = BoundaryInt<TransferPriorityRankTag>
public typealias TransferDirectionName = BoundaryString<TransferDirectionNameTag>
public typealias CacheEntryAge = BoundaryDuration<CacheEntryAgeTag>
public typealias CachePatternName = BoundaryString<CachePatternNameTag>
public typealias CachePreloadPriority = BoundaryInt<CachePreloadPriorityTag>
public typealias CachePreloadConcurrency = BoundaryInt<CachePreloadConcurrencyTag>
public typealias StorageSizeBytes = BoundaryInt64<StorageSizeBytesTag>
public typealias CacheHitCount = BoundaryInt64<CacheHitCountTag>
public typealias CacheMissCount = BoundaryInt64<CacheMissCountTag>
public typealias CacheEvictionCount = BoundaryInt64<CacheEvictionCountTag>
public typealias CacheHitRatioMetric = BoundaryDouble<CacheHitRatioMetricTag>
public typealias CacheDirectoryURL = BoundaryURL<CacheDirectoryURLTag>
public typealias CompressionEnabledFlag = BoundaryBool<CompressionEnabledFlagTag>
public typealias CacheExtensionFactor = BoundaryDouble<CacheExtensionFactorTag>
public typealias HeaderNameValidationFlag = BoundaryBool<HeaderNameValidationFlagTag>
public typealias HeaderValueValidationFlag = BoundaryBool<HeaderValueValidationFlagTag>
public typealias HeaderSanitizationFlag = BoundaryBool<HeaderSanitizationFlagTag>
public typealias HeaderValueLengthLimit = BoundaryInt<HeaderValueLengthLimitTag>
public typealias HeaderCountLimit = BoundaryInt<HeaderCountLimitTag>
public typealias DangerousHeaderRemovalFlag = BoundaryBool<DangerousHeaderRemovalFlagTag>
public typealias DangerousHeaderName = BoundaryString<DangerousHeaderNameTag>
public typealias HeaderValidationDecision = BoundaryBool<HeaderValidationDecisionTag>
public typealias CertificateHash = BoundaryString<CertificateHashTag>
public typealias PinnedDomain = BoundaryString<PinnedDomainTag>
public typealias BackupCertificateAllowance = BoundaryBool<BackupCertificateAllowanceTag>
public typealias PinnedKeyRequirement = BoundaryBool<PinnedKeyRequirementTag>
public typealias TLSChainValidationFlag = BoundaryBool<TLSChainValidationFlagTag>
public typealias TLSHostnameValidationFlag = BoundaryBool<TLSHostnameValidationFlagTag>
public typealias CACertificateData = BoundaryData<CACertificateDataTag>
public typealias ErrorContextMetadataKey = BoundaryString<ErrorContextMetadataKeyTag>
public typealias ErrorContextMetadataValue = BoundaryString<ErrorContextMetadataValueTag>
public typealias JitterFactor = BoundaryDouble<JitterFactorTag>
public typealias TransferSpeedText = BoundaryString<TransferSpeedTextTag>
public typealias TransferTimeRemainingText = BoundaryString<TransferTimeRemainingTextTag>
public typealias FileOperationDescription = BoundaryString<FileOperationDescriptionTag>
public typealias TransferProgressSummaryText = BoundaryString<TransferProgressSummaryTextTag>
public typealias CacheExpirationFlag = BoundaryBool<CacheExpirationFlagTag>
public typealias CacheWarmSuccessFlag = BoundaryBool<CacheWarmSuccessFlagTag>
public typealias CacheEntryCount = BoundaryInt<CacheEntryCountTag>
public typealias CachePrefetchDepth = BoundaryInt<CachePrefetchDepthTag>
public typealias CachePrefetchCount = BoundaryInt<CachePrefetchCountTag>
public typealias AsyncSemaphorePermitCount = BoundaryInt<AsyncSemaphorePermitCountTag>
public typealias CacheEvictionDecision = BoundaryBool<CacheEvictionDecisionTag>
public typealias CacheExtensionOnAccessFlag = BoundaryBool<CacheExtensionOnAccessFlagTag>
public typealias KeychainServiceName = BoundaryString<KeychainServiceNameTag>
public typealias KeychainAccessGroup = BoundaryString<KeychainAccessGroupTag>
public typealias KeychainSynchronizableFlag = BoundaryBool<KeychainSynchronizableFlagTag>
public typealias KeychainItemKey = BoundaryString<KeychainItemKeyTag>
public typealias KeychainStringValue = BoundaryString<KeychainStringValueTag>
public typealias KeychainDataValue = BoundaryData<KeychainDataValueTag>
public typealias KeychainItemExistenceFlag = BoundaryBool<KeychainItemExistenceFlagTag>
public typealias OAuthClientIdentifier = BoundaryString<OAuthClientIdentifierTag>
public typealias KeychainStatusCode = BoundaryInt<KeychainStatusCodeTag>
public typealias RequestRecordingEnabledFlag = BoundaryBool<RequestRecordingEnabledFlagTag>
public typealias MockVerificationCount = BoundaryInt<MockVerificationCountTag>
public typealias MockUnixTimestamp = BoundaryDuration<MockUnixTimestampTag>
public typealias MockTimeAdjustment = BoundaryDuration<MockTimeAdjustmentTag>
public typealias MockRequestIndex = BoundaryInt<MockRequestIndexTag>
public typealias MockResponseIndex = BoundaryInt<MockResponseIndexTag>
public typealias MockContextIdentifier = BoundaryUUID<MockContextIdentifierTag>
public typealias MockURLPattern = BoundaryString<MockURLPatternTag>
public typealias MockPredicateMatchFlag = BoundaryBool<MockPredicateMatchFlagTag>
public typealias MockResponseDelay = BoundaryDuration<MockResponseDelayTag>
public typealias ExpectationDescriptionText = BoundaryString<ExpectationDescriptionTextTag>
public typealias ExpectationFulfillmentFlag = BoundaryBool<ExpectationFulfillmentFlagTag>
public typealias TestingSupportEnabledFlag = BoundaryBool<TestingSupportEnabledFlagTag>
public typealias TestingToolName = BoundaryString<TestingToolNameTag>
public typealias TestingUtilitiesVersion = BoundaryString<TestingUtilitiesVersionTag>
public typealias BDDFilterMatchFlag = BoundaryBool<BDDFilterMatchFlagTag>
public typealias BDDDefinitionAvailabilityFlag = BoundaryBool<BDDDefinitionAvailabilityFlagTag>
public typealias BDDPassedFlag = BoundaryBool<BDDPassedFlagTag>
public typealias BDDFailedFlag = BoundaryBool<BDDFailedFlagTag>
public typealias BDDStepCaptureText = BoundaryString<BDDStepCaptureTextTag>
